name: UVVillagers
main: net.uvnode.uvvillagers.UVVillagers
version: 1.2.2.1
load: POSTWORLD
author: jcornwellshiel
authors: [Northcode]
website: uv-node.net
softdepend: [dynmap, pluginmetrics]

commands:
  uvv:
    description: UVVillagers commands
    usage: /uvv [reload,save,list,nearby,current,siege,siegeinfo,rename]

permissions:
  uvv.*:
    description: Gives access to all UVVillagers commands
    children:
      uvv.admin: true
      uvv.villageinfo: true
      uvv.siegeinfo: true
      uvv.rename: true
  uvv.admin:
    description: Gives access to reload, save, toggle debug mode, and start sieges.
    default: op
  uvv.villageinfo:
    description: Gives access to retrieve village info.
    default: true
  uvv.siegeinfo:
    description: Gives access to siege info.
    default: true
  uvv.rename:
    description: Rename your village.
    default: true
  uvv.tribute:
    description: Allows the player to collect UVVillage tributes.
    default: true
  uvv.reputation:
    description: Allows the player to lose/gain UVVillage reputation.
    default: true